Import-Module ActiveDirectory
Import-Module GroupPolicy

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$OU_GPO_Tool = New-Object System.Windows.Forms.Form
$screen = [System.Windows.Forms.Screen]::PrimaryScreen.WorkingArea
$OU_GPO_Tool.Size = New-Object System.Drawing.Size(1450, $screen.Height)
$OU_GPO_Tool.AutoSize = $true
$OU_GPO_Tool.AutoScale = $true
$OU_GPO_Tool.Text = "AD_OU-GPO_Tool"
$OU_GPO_Tool.BackColor = "#ffffff"
$OU_GPO_Tool.StartPosition = "CenterScreen"


# General Stufff ----------------------------------------------------------------------------------------------------------------------------------

# Title
$title = New-Object System.Windows.Forms.Label
$title.Text = "AD_OU-GPO_Tool"
$title.AutoSize = $true
$title.Width = 25
$title.Height = 10
$title.Location = New-Object System.Drawing.Point(20, 20)
$title.Font = 'Microsoft Sans Serif,13'
$OU_GPO_Tool.Controls.Add($title)

# Icon
$iconBase64 = 'AAABAAEAQEAAAAEAIAAoQgAAFgAAACgAAABAAAAAgAAAAAEAIAAAAAAAAEAAABMLAAATCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP922hz/ed6q/3je8f943vH/ed6s/3zcJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/3baHP953qr/eN7x/3je8f953qz/fNwlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/dtoc/3neqv943vH/eN7x/3nerP983CUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP922hz/ed6q/3je8f943vH/ed6s/3zcJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP983if/eN3t/3ne//953v//ed7//3ne//943e3/fNwlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/3zeJ/943e3/ed7//3ne//953v//ed7//3jd7f983CUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/fN4n/3jd7f953v//ed7//3ne//953v//eN3t/3zcJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP983if/eN3t/3ne//953v//ed7//3ne//943e3/fNwlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD9eNqu/Xja//142rb/e9sd/3vbHf132bf9eNr//XjZrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP142q79eNr//Xjatv972x3/e9sd/XfZt/142v/9eNmsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Xjarv142v/9eNq2/3vbHf972x39d9m3/Xja//142awAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD9eNqu/Xja//142rb/e9sd/3vbHf132bf9eNr//XjZrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+nfV8vt31v//dtEcAAAAAAAAAAD/e9Md+3fW//p31fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD6d9Xy+3fW//920RwAAAAAAAAAAP970x37d9b/+nfV8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPp31fL7d9b//3bRHAAAAAAAAAAA/3vTHft31v/6d9XwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+nfV8vt31v//dtEcAAAAAAAAAAD/e9Md+3fW//p31fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPh10ur4dtL/9XbRHAAAAAAAAAAA9nLTHfh20v/4dtLpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+HXS6vh20v/1dtEcAAAAAAAAAAD2ctMd+HbS//h20ukAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4ddLq+HbS//V20RwAAAAAAAAAAPZy0x34dtL/+HbS6QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPh10ur4dtL/9XbRHAAAAAAAAAAA9nLTHfh20v/4dtLpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD1dc6p9nXO//Z0zbX1dtEc9XbRHPZ1zbb2dc7/9XXOpwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPV1zqn2dc7/9nTNtfV20Rz1dtEc9nXNtvZ1zv/1dc6nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9XXOqfZ1zv/2dM219XbRHPV20Rz2dc229nXO//V1zqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD1dc6p9nXO//Z0zbX1dtEc9XbRHPZ1zbb2dc7/9XXOpwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8HTMI/R0yuj0dMr/9HTK//R0yv/0dMr/9HTK6PdwyiIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwdMwj9HTK6PR0yv/0dMr/9HTK//R0yv/0dMro93DKIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPB0zCP0dMro9HTK//R0yv/0dMr/9HTK//R0yuj3cMoiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8HTMI/R0yuj0dMr/9HTK//R0yv/0dMr/9HTK6PdwyiIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwcMMi8nPGo/Jzxv/yc8b/8nPGo/BwwyIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPBwwyLyc8aj8nPG//Jzxv/yc8aj8HDDIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8HDDIvJzxqPyc8b/8nPG//JzxqPwcMMiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwcMMi8nPGo/Jzxv/yc8b/8nPGo/BwwyIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwccHy8HLC/+x2vxwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7XLBHfBywv/wcsHxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8HHB8vBywv/sdr8cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO1ywR3wcsL/8HLB8QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7nC9rO5wvv/ub7617G2/HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7G2/HO5wvrbucL7/7nC+qgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO5wvazucL7/7m++textvxwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOxtvxzucL627nC+/+5wvqoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO1yuB3rbrrt7G+6/+xvuv/rbrnv62+6uu1vukcAAAAAAAAAAO1tu0jrb7q662657+xvuv/sb7r/62667extthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADtcrgd62667exvuv/sb7r/62657+tvurrtb7pHAAAAAAAAAADtbbtI62+6uutuue/sb7r/7G+6/+tuuu3sbbYcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7XK4Hepttqzpbbby6m62/+putv/pbrX+6m61feputn/qbrb/6m62/+putv/pbbby6m21rutvtycAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO1yuB3qbbas6W228uputv/qbrb/6W61/uputX3qbrZ/6m62/+putv/qbrb/6W228uptta7rb7cnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOdorRbnbLF252yx++htsv/obbL/52yx++dssXbnaK0WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADnaK0W52yxdudssfvobbL/6G2y/+dssfvnbLF252itFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOVrrnnmbK7/5myu/+VsrngAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADla6555myu/+Zsrv/lbK54AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADjaqlx5Guq/+Rrqv/ja6pwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA42qpceRrqv/ka6r/42uqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADhaaVE4Wml8+Jqpv/iaqb/4Wml8+FppUQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4WmlROFppfPiaqb/4mqm/+FppfPhaaVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADeaKF932mi/99pov/faaL/32mi/99pov/faaL/3mihfQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3mihfd9pov/faaL/32mi/99pov/faaL/32mi/95ooX0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADeaZxG3Wie/95mnv/vPKz//B63//set//vPK3/3mae/91onv/eaZxGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3mmcRt1onv/eZp7/7zys//wet//7Hrf/7zyt/95mnv/daJ7/3mmcRgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA22aZuttnmv/uTKT//zSu//80rv//NK7//zSu/+5MpP/bZ5r/22eauQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANtmmbrbZ5r/7kyk//80rv//NK7//zSu//80rv/uTKT/22ea/9tnmrkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANllluzZZpb/+1ef//9WoP//VqD//1ag//9WoP/7WJ//2WaW/9lmlesAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZZZbs2WaW//tXn///VqD//1ag//9WoP//VqD/+1if/9lmlv/ZZpXrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADXZZL012WS//t2k///eJP//3iT//94k///eJP/+3aT/9dlkv/XZJHzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA12WS9Ndlkv/7dpP//3iT//94k///eJP//3iT//t2k//XZZL/12SR8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1WSOv9Vkj//rgYr//5qG//+ahv//mob//5qG/+uBiv/VZI//1WOPvQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANVkjr/VZI//64GK//+ahv//mob//5qG//+ahv/rgYr/1WSP/9Vjj70AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANNji0DTY4v/1GWL/+uTgf/7s3v/+7N7/+qSgv/UZYv/02OL/9JhiT8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADTY4tA02OL/9Rli//rk4H/+7N7//uze//qkoL/1GWL/9Nji//SYYk/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0WKHfNBihv7RYof/0WKH/9Fih//RYof/0GKG/tFih3oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANFih3zQYob+0WKH/9Fih//RYof/0WKH/9Bihv7RYod6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQYYJMzmGCv89hg//PYYP/zmGCv89ihEsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0GGCTM5hgr/PYYP/z2GD/85hgr/PYoRLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMX37zzWB//8xbehkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMW3oZzWB//81ff/IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyl56v8tfe//LXnp3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzF97eMtfe//KXnq9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMpcd03JXnf/yF52+chcdnbEYnUaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEYnUayV54d8hedvnJXnf/yV11TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxVtyhsZcc//GXHP/xlxz/8Zcc//GXHP/xlxz/8Zcc//GXHP/xlxz/8Zbc+/FW3O6xV1yRwAAAAAAAAAAxlxxSMVbc7rGW3Pvxlxz/8Zcc//GXHP/xlxz/8Zcc//GXHP/xlxz/8Zcc//GXHP/xVxzhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDWXBNxFpuv8RabvTEW2//xFtv/8Rbb//EW2//xFtv/8Rbb//EW2//xFtv/8Nbb/7DW259xFpuf8Rbb//EW2//xFtv/8Rbb//EW2//xFtv/8Rbb//EW2//xFtv/8RabvTDW2++wlpuTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxl5nG8Faa3nBWmr5wlpr/8Jaa//BWmr5wVlqeMRYaxoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv1hnecBZZ//AWWf/v1lmeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALxVXhu+WGP/vlhj/7pYYhoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvFdf/7xXX/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAulZbZLpWW/+6Vlv/uVVaYwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALdVV+y4VVf/uFVX/7dVV+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtlVVKrVTU4+2VFP/tlRT/7ZUU/+2VFP/tVNTj7ZVVSoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqVVUGs1JPkbRSTvy0U0//tFNP/7RTT/+0U0//tFNP/7RTT/+0Uk78tFNPkKpVVQYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC2SEgHslFLu7JSS/+yUUr5slFKk7JQTDmqVVUMqlVVDLJQTDmxUkuVslFK+bJSS/+xUUq5qlVVBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr1FHk7BRR/+vUEbkr09FMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALJRRzKvUUflsFFH/69QRpEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArVFFLK1PQv2sUEL4r09FMAAAAACtUT8crE9Dqq1QQvGtUELxrVBCrKxSRCUAAAAArVFCMq1PQvmtT0L9qk5CKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKtPQJOrT0D/q05AkgAAAACqTkEnq04/7atPQP+rT0D/q09A/6tPQP+rTj/trEs+JQAAAACrTj+Vq09A/6pPP5EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACpTTvWqU48/6ZOPDcAAAAAqE08rqlOPP+pTjy2p089HadPPR2oTju3qU48/6lOO6wAAAAAqkw6OalOPP+pTjzUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApk049adNOP+qVT8MAAAAAKZMN/KnTTj/o0g2HAAAAAAAAAAAp080HadNOP+mTDjwAAAAAKNINg6nTTj/pkw38wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKRLNPOlTDT/qlUqDAAAAAClSzPypUw0/6NINhwAAAAAAAAAAKdPNB2lTDT/pUwz8QAAAACqVSoMpUw0/6VLM/IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACiSy/Vo0sw/6VLLzYAAAAAo0svrKNLMP+jSi+1o0gtHKNILRyiSy+2o0sw/6NLMKoAAAAAo0gyOKNLMP+jSjDTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoUoskKFKLP+hSSuRAAAAAJ5GKx2hSiztoUos/6FKLP+hSiz/oUos/6FKLO2jSC0cAAAAAKBKLJShSiz/oUksjgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJxFKCyeRyj8n0co+J1GJS8AAAAAnkYrHZ5IKKyfRyjyn0co8p5HJ66cRycnAAAAAKFIKTGeRyf5nkco/KBHKSsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnUYjlZ1HJP+cRiPknUYlLwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ9FJTCcRiPknUck/51HJJIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKpVKgabRiC9m0Yg/5tFH/iaRh+RmUUgN6JFFwuiRRcLmUUgN5pFH5OaRR/5m0Yg/5pGILyqVSoGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqlUqBphEG5WZRBz9mUUc/5lFHP+ZRRz/mUUc/5lFHP+ZRRz/mEQc/JhFG5OqVSoGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkUXLJZDGJCXRBjUlkMY9JZDGPSXRBjUlkMYkJZFFywAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////////////////////////////////////////////////////////wP8D/A/wP/+AfgH4B+Af/4B+AfgH4B//jH4x+MfjH/+MfjH4x+Mf/4B+AfgH4B//gH4B+AfgH//A/wP8D/A///H/j/8f+P//8P8P/w/w///wGA//AYD///gAH/+AAf///wD///AP////w////D/////D///8P////4H///gf////AP//8A////4Af//gB////gB//+AH///+AH//4Af///4Af//gB////gB//+AH///+AH//4Af///8A///wD////4H///gf////4////H/////j///8f////+D///B/////8ABgAP/////4AAAB///////8A/////////8P/////////w//////////n/////////8P/////////w/////////8A/////////AA////////4AB////////h+H///////8IEP///////xAI////////EAj///////8RiP///////xGI////////EAj///////8QCP///////wgQ////////h+H///////+AAf///////8AD////////8A////////////////////////////////////////////////////////////////////8='
$iconBytes = [Convert]::FromBase64String($iconBase64)
$stream = New-Object System.IO.MemoryStream($iconBytes, 0, $iconBytes.Length)
$bitmap = [System.Drawing.Bitmap]::FromStream($stream)
$OU_GPO_Tool.Icon = [System.Drawing.Icon]::FromHandle($bitmap.GetHicon())

# transparent Label
$focusLabel = New-Object System.Windows.Forms.Label
$focusLabel.Size = New-Object System.Drawing.Size(0, 0)
$focusLabel.Location = New-Object System.Drawing.Point(0, 0)
$OU_GPO_Tool.Controls.Add($focusLabel)
# set in focus
$OU_GPO_Tool.Add_Shown({ $focusLabel.Focus() })

# Descriptions
$descriptionOUChoice = New-Object System.Windows.Forms.Label
$descriptionOUChoice.Text = "Choose an existing OU:"
$descriptionOUChoice.AutoSize = $false
$descriptionOUChoice.Width = 425
$descriptionOUChoice.Height = 20
$descriptionOUChoice.Location = New-Object System.Drawing.Point(20, 50)
$descriptionOUChoice.Font = 'Microsoft Sans Serif,10'
$OU_GPO_Tool.Controls.Add($descriptionOUChoice)

$descriptionStatus = New-Object System.Windows.Forms.Label
$descriptionStatus.Text = "Status:"
$descriptionStatus.AutoSize = $false
$descriptionStatus.Width = 225
$descriptionStatus.Height = 20
$descriptionStatus.Location = New-Object System.Drawing.Point(745, 50)
$descriptionStatus.Font = 'Microsoft Sans Serif,10'
$OU_GPO_Tool.Controls.Add($descriptionStatus)

$descriptionOUCreate = New-Object System.Windows.Forms.Label
$descriptionOUCreate.Text = "Create a new OU:"
$descriptionOUCreate.AutoSize = $false
$descriptionOUCreate.Width = 425
$descriptionOUCreate.Height = 20
$descriptionOUCreate.Location = New-Object System.Drawing.Point(20, 170)
$descriptionOUCreate.Font = 'Microsoft Sans Serif,10'
$OU_GPO_Tool.Controls.Add($descriptionOUCreate)

$descriptionInput = New-Object System.Windows.Forms.Label
$descriptionInput.Text = "Insert the GPOs for the chosen or new created OU here:"
$descriptionInput.AutoSize = $false
$descriptionInput.Width = 425
$descriptionInput.Height = 20
$descriptionInput.Location = New-Object System.Drawing.Point(20, 290)
$descriptionInput.Font = 'Microsoft Sans Serif,10'
$OU_GPO_Tool.Controls.Add($descriptionInput)

$descriptionOutput = New-Object System.Windows.Forms.Label
$descriptionOutput.Text = "The GPOs of the chosen OU:"
$descriptionOutput.AutoSize = $false
$descriptionOutput.Width = 425
$descriptionOutput.Height = 20
$descriptionOutput.Location = New-Object System.Drawing.Point(20, 605)
$descriptionOutput.Font = 'Microsoft Sans Serif,10'
$OU_GPO_Tool.Controls.Add($descriptionOutput)

$descriptionReset = New-Object System.Windows.Forms.Label
$descriptionReset.Text = "(Resets everything to default)"
$descriptionReset.AutoSize = $false
$descriptionReset.Width = 425
$descriptionReset.Height = 20
$descriptionReset.Location = New-Object System.Drawing.Point(500, 20)
$descriptionReset.Font = 'Microsoft Sans Serif,10'
$OU_GPO_Tool.Controls.Add($descriptionReset)


# Dropdown Boxes ----------------------------------------------------------------------------------------------------------------------------------

# Sites
$siteOUDrop = New-Object System.Windows.Forms.ComboBox
$siteOUDrop.Text = "Choose a Department/Site OU"
$siteOUDrop.Width = 500
$siteOUDrop.Location = New-Object System.Drawing.Point(20, 75)
$siteOUDrop.Font = 'Microsoft Sans Serif,10'
$siteOUDrop.DisplayMember = 'Name'
$siteOUDrop.ValueMember = 'DistinguishedName'
$OU_GPO_Tool.Controls.Add($siteOUDrop) 

# User
$userOUDrop = New-Object System.Windows.Forms.ComboBox
$userOUDrop.Text = "Choose an User OU"
$userOUDrop.Width = 500
$userOUDrop.Location = New-Object System.Drawing.Point(20, 100)
$userOUDrop.Font = 'Microsoft Sans Serif,10'
$userOUDrop.DisplayMember = 'Name'
$userOUDrop.ValueMember = 'DistinguishedName'
$OU_GPO_Tool.Controls.Add($userOUDrop) 

# Computer
$computerOUDrop = New-Object System.Windows.Forms.ComboBox
$computerOUDrop.Text = "Choose a Computer OU"
$computerOUDrop.Width = 500 
$computerOUDrop.Location = New-Object System.Drawing.Point(20, 125)
$computerOUDrop.Font = 'Microsoft Sans Serif,10'
$computerOUDrop.DisplayMember = 'Name'
$computerOUDrop.ValueMember = 'DistinguishedName'
$OU_GPO_Tool.Controls.Add($computerOUDrop) 


# AD-Query ---------------------------------------------------------------------------------------------------------------------------------------
# Change the -SearchBase for your purpose! (will not work without it)
$sites = Get-ADOrganizationalUnit -SearchBase 'OU="Sites/Department",DC="XXXXX",DC="dom/com"' -Filter * | Where-Object { $_.DistinguishedName -match '^ou=[^,]+,ou=Sites/Department,dc="XXXXX",dc="dom/com"$' }
foreach ($site in $sites) {
    $siteOUDrop.Items.Add([PSCustomObject]@{'Name' = $site.Name; 'DistinguishedName' = $site.DistinguishedName })
}

$siteOUDrop.add_SelectedIndexChanged({
        $selectedSite = $siteOUDrop.SelectedItem.DistinguishedName
        $statusTextbox.Text += "Switched to Site/Department: " + $siteOUDrop.SelectedItem.Name + "`r`n"

        # Refresh of the user and computer dropdown boxes based on the chosen site/department OU 
        $userOUDrop.Items.Clear()
        $computerOUDrop.Items.Clear()
        $userOUs = Get-ADOrganizationalUnit  -SearchBase "OU=User,$selectedSite" -Filter *
        $computerOUs = Get-ADOrganizationalUnit -SearchBase "OU=Computer,$selectedSite" -Filter *
        foreach ($OU in $userOUs) {
            $userOUDrop.Items.Add([PSCustomObject]@{'Name' = $OU.Name; 'DistinguishedName' = $OU.DistinguishedName })
        }
        foreach ($OU in $computerOUs) {
            $computerOUDrop.Items.Add([PSCustomObject]@{'Name' = $OU.Name; 'DistinguishedName' = $OU.DistinguishedName })
        }
    })


# Text Boxes ----------------------------------------------------------------------------------------------------------------------------

# Status
$statusTextbox = New-Object System.Windows.Forms.TextBox
$statusTextbox.Location = New-Object System.Drawing.Point(745, 75)
$statusTextbox.Size = New-Object System.Drawing.Size(660, 855)
$statusTextbox.Multiline = $true
$statusTextbox.ReadOnly = $true
$statusTextbox.ScrollBars = [System.Windows.Forms.ScrollBars]::Vertical
$OU_GPO_Tool.Controls.Add($statusTextbox)

# Name new OU
$newOUTextbox = New-Object System.Windows.Forms.TextBox
$newOUTextbox.Location = New-Object System.Drawing.Point(20, 195)
$newOUTextbox.Size = New-Object System.Drawing.Size(500, 100)
$newOUTextbox.Text = "Name new OU"
$newOUTextbox.Font = 'Microsoft Sans Serif,10'
$OU_GPO_Tool.Controls.Add($newOUTextbox)

# Input User GPO
$inputUserTextbox = New-Object System.Windows.Forms.TextBox
$inputUserTextbox.Location = New-Object System.Drawing.Point(20, 315)
$inputUserTextbox.Size = New-Object System.Drawing.Size(350, 220)
$inputUserTextbox.Multiline = $true 
$inputUserTextbox.ScrollBars = [System.Windows.Forms.ScrollBars]::Vertical
$OU_GPO_Tool.Controls.Add($inputUserTextbox)

# Input Computer GPO
$inputComputerTextbox = New-Object System.Windows.Forms.TextBox
$inputComputerTextbox.Location = New-Object System.Drawing.Point(375, 315)
$inputComputerTextbox.Size = New-Object System.Drawing.Size(350, 220)
$inputComputerTextbox.Multiline = $true 
$inputComputerTextbox.ScrollBars = [System.Windows.Forms.ScrollBars]::Vertical
$OU_GPO_Tool.Controls.Add($inputComputerTextbox)

# Output GPO
$outputTextbox = New-Object System.Windows.Forms.TextBox
$outputTextbox.Location = New-Object System.Drawing.Point(20, 630)
$outputTextbox.Size = New-Object System.Drawing.Size(705, 300)
$outputTextbox.ReadOnly = $true
$outputTextbox.Multiline = $true 
$outputTextbox.ScrollBars = [System.Windows.Forms.ScrollBars]::Vertical
$OU_GPO_Tool.Controls.Add($outputTextbox)


# Progressbar ------------------------------------------------------------------------------------------------------------------

$progressBar = New-Object System.Windows.Forms.ProgressBar
$progressBar.Location = New-Object System.Drawing.Point(1000, 40)
$progressBar.Size = New-Object System.Drawing.Size(405, 23)
$OU_GPO_Tool.Controls.Add($progressBar)


# Functions GPO add User/Computer ----------------------------------------------------------------------------------------------

# Function for adding user-OUs
function Add-UserGPOs {
    param($selectedOU, $GPOsToAdd)

    foreach ($GPOName in $GPOsToAdd) {
        try {
            $GPO = Get-GPO -Name $GPOName
            New-GPLink -Guid $GPO.Id -Target $selectedOU -LinkEnabled Yes
            $statusTextbox.Text += "The User GPO '$GPOName' was added successfully.`r`n"
            $statusTextbox.Text += "=========================================================================================================="
        }
        catch {
            $statusTextbox.Text += "The User GPO '$GPOName' couldn't be found.`r`n"
            $statusTextbox.Text += "=========================================================================================================="
        }
    }
}

# Function for adding computer-GPOs
function Add-ComputerGPOs {
    param($selectedOU, $GPOsToAdd)

    foreach ($GPOName in $GPOsToAdd) {
        try {
            $GPO = Get-GPO -Name $GPOName
            New-GPLink -Guid $GPO.Id -Target $selectedOU -LinkEnabled Yes
            $statusTextbox.Text += "The Computer GPO '$GPOName' was added successfully.`r`n"
            $statusTextbox.Text += "=========================================================================================================="
        }
        catch {
            $statusTextbox.Text += "The Computer GPO '$GPOName' couldn't be found.`r`n"
            $statusTextbox.Text += "=========================================================================================================="
        }
    }
}

# Buttons ----------------------------------------------------------------------------------------------------------------------

# New OU Button
$newOUButton = New-Object System.Windows.Forms.Button
$newOUButton.Location = New-Object System.Drawing.Point(395, 220)
$newOUButton.Size = New-Object System.Drawing.Size(125, 23)
$newOUButton.Text = "Create new OU"
$OU_GPO_Tool.Controls.Add($newOUButton)

$newOUButton.add_Click({
        $newOUName = $newOUTextbox.Text
        if ($userOUDrop.SelectedItem -ne $null) {
            $selectedOU = $userOUDrop.SelectedItem.DistinguishedName
        }
        elseif ($computerOUDrop.SelectedItem -ne $null) {
            $selectedOU = $computerOUDrop.SelectedItem.DistinguishedName
        }

        if ($selectedOU -ne $null) {
            $newOUDN = "OU=$newOUName,$selectedOU"
            try {
  
                # Check if the OU is already existing
                Get-ADOrganizationalUnit -Identity $newOUDN | Out-Null
                $statusTextbox.Text += "The OU '$newOUName' already exists.`r`n"

            }
            catch {
  
                # The OU doesn't exist, so create it
                New-ADOrganizationalUnit -Name $newOUName -Path $selectedOU
                $statusTextbox.Text += "The OU '$newOUName' gets created...`r`n"
                $statusTextbox.Text += "$newOUDN `r`n"
                $statusTextbox.Text += "Please wait...`r`n"
  
                # Deactivate protection from accidental deletion (optional) (for my use case important)
                Get-ADObject -Identity  $newOUDN | Set-ADObject -ProtectedFromAccidentalDeletion:$false
  
                # Block GP inheritance (optional) (for my use case important)
                Set-GPInheritance -Target $newOUDN -IsBlocked Yes

                # Start of the "progress"bar (optional) (only needed if u want to use one of the optional functions above (timing problem -> AD can be slow sometimes))
                $progressBar.Value = 0
                Start-Sleep 5
                $progressBar.Value = 25
                Start-Sleep 5
                $progressBar.Value = 50
                Start-Sleep 5
                $progressBar.Value = 75
                Start-Sleep 5
                $progressBar.Value = 95
                Start-Sleep 1
                $progressBar.Value = 100
                $statusTextbox.Text += "DONE! The OU $newOUName was created! `r`n"
                $statusTextbox.Text += "=========================================================================================================="
                $progressBar.Value = 0
            }
        }
        else {
            $statusTextbox.Text += "Please choose an OU from the dropdown boxes.`r`n"
            $statusTextbox.Text += "=========================================================================================================="
        }
    })

# New User and Computer OU
$newUaCOUButton = New-Object System.Windows.Forms.Button
$newUaCOUButton.Location = New-Object System.Drawing.Point(125, 220)
$newUaCOUButton.Size = New-Object System.Drawing.Size(225, 23)
$newUaCOUButton.Text = "Create a new User and Computer OU"
$OU_GPO_Tool.Controls.Add($newUaCOUButton)

$newUaCOUButton.add_Click({
        $newOUName = $newOUTextbox.Text
        $selectedUserOU = $userOUDrop.SelectedItem.DistinguishedName
        $selectedComputerOU = $computerOUDrop.SelectedItem.DistinguishedName

        if ($selectedUserOU -ne $null -and $selectedComputerOU -ne $null) {
            $newUserOUDN = "OU=$newOUName,$selectedUserOU"
            $newComputerOUDN = "OU=$newOUName,$selectedComputerOU"
            try {
  
                # Check if the OUs are already existing
                Get-ADOrganizationalUnit -Identity $newUserOUDN | Out-Null
                Get-ADOrganizationalUnit -Identity $newComputerOUDN | Out-Null
                $statusTextbox.Text += "The OU '$newOUName' already exists.`r`n"

            }
            catch {

                # The OUs dont exist, so create them
                New-ADOrganizationalUnit -Name $newOUName -Path $selectedUserOU
                New-ADOrganizationalUnit -Name $newOUName -Path $selectedComputerOU
                $statusTextbox.Text += "The OUs '$newOUName' are getting created...`r`n"
                $statusTextbox.Text += "$newUserOUDN `r`n"
                $statusTextbox.Text += "$newComputerOUDN `r`n"
                $statusTextbox.Text += "Please wait...`r`n"
  
                # Deactivate protection from accidental deletion (optional) (for my use case important)
                Get-ADObject -Identity  $newUserOUDN | Set-ADObject -ProtectedFromAccidentalDeletion:$false
                Get-ADObject -Identity  $newComputerOUDN | Set-ADObject -ProtectedFromAccidentalDeletion:$false
  
                # Block GP inheritance (optional) (for my use case important)
                Set-GPInheritance -Target $newUserOUDN -IsBlocked Yes
                Set-GPInheritance -Target $newComputerOUDN -IsBlocked Yes
  
                # Start of the "progress"bar (optional) (only needed if u want to use one of the optional functions above (timing problem -> AD can be slow sometimes))
                $progressBar.Value = 0
                Start-Sleep 5
                $progressBar.Value = 25
                Start-Sleep 5
                $progressBar.Value = 50
                Start-Sleep 5
                $progressBar.Value = 75
                Start-Sleep 5
                $progressBar.Value = 95
                Start-Sleep 1
                $progressBar.Value = 100
                $statusTextbox.Text += "DONE! The OUs $newOUName were created! `r`n"
                $statusTextbox.Text += "=========================================================================================================="
                $progressBar.Value = 0
            }
        }
        else {
            $statusTextbox.Text += "Please choose both OUs from the dropdown boxes. (User + Computer) `r`n"
            $statusTextbox.Text += "=========================================================================================================="
        }
    })

# Button for adding User-GPOs
$addUserButton = New-Object System.Windows.Forms.Button
$addUserButton.Location = New-Object System.Drawing.Point(215, 542)
$addUserButton.Size = New-Object System.Drawing.Size(155, 23)
$addUserButton.Text = "Add User GPOs"
$OU_GPO_Tool.Controls.Add($addUserButton)

$addUserButton.add_Click({
        if ($userOUDrop.SelectedItem -ne $null) {
            # Calling the GPOs from the inputTextbox
            $userGPOsToAdd = $inputUserTextbox.Text -split "`r`n"

            # Call the function in order to add the user GPOs
            Add-UserGPOs -selectedOU $userOUDrop.SelectedItem.DistinguishedName -GPOsToAdd $userGPOsToAdd
        }
        else {
            $statusTextbox.Text += "Please choose an User OU from the dropdown boxes.`r`n"
            $statusTextbox.Text += "=========================================================================================================="
        }
    })

# Button for adding Computer-GPOs
$addComputerButton = New-Object System.Windows.Forms.Button
$addComputerButton.Location = New-Object System.Drawing.Point(375, 542)
$addComputerButton.Size = New-Object System.Drawing.Size(155, 23)
$addComputerButton.Text = "Add Computer GPOs"
$OU_GPO_Tool.Controls.Add($addComputerButton)

$addComputerButton.add_Click({
        if ($computerOUDrop.SelectedItem -ne $null) {
            # Calling the GPOs from the inputTextbox
            $computerGPOsToAdd = $inputComputerTextbox.Text -split "`r`n"

            # Call the function in order to add the computer GPOs
            Add-ComputerGPOs -selectedOU $computerOUDrop.SelectedItem.DistinguishedName -GPOsToAdd $computerGPOsToAdd
        }
        else {
            $statusTextbox.Text += "Please choose a Computer OU from the dropdown boxes.`r`n"
            $statusTextbox.Text += "=========================================================================================================="
        }
    })

# Button for adding user and computer GPOs
$addBothButton = New-Object System.Windows.Forms.Button
$addBothButton.Location = New-Object System.Drawing.Point(270, 570)
$addBothButton.Size = New-Object System.Drawing.Size(200, 23)
$addBothButton.Text = "Add both GPOs"
$OU_GPO_Tool.Controls.Add($addBothButton)

$addBothButton.add_Click({
        if ($userOUDrop.SelectedItem -ne $null -and $computerOUDrop.SelectedItem -ne $null) {
            # Calling the GPOs from the inputTextboxes
            $userGPOsToAdd = $inputUserTextbox.Text -split "`r`n"
            $computerGPOsToAdd = $inputComputerTextbox.Text -split "`r`n"

            # Call the functions in order to add both GPOs
            Add-UserGPOs -selectedOU $userOUDrop.SelectedItem.DistinguishedName -GPOsToAdd $userGPOsToAdd
            Add-ComputerGPOs -selectedOU $computerOUDrop.SelectedItem.DistinguishedName -GPOsToAdd $computerGPOsToAdd
        }
        else {
            $statusTextbox.Text += "Please choose an User and a Computer OU from the dropdown boxes.`r`n"
            $statusTextbox.Text += "=========================================================================================================="
        }
    })

# GPO View Button
$gpoViewButton = New-Object System.Windows.Forms.Button
$gpoViewButton.Location = New-Object System.Drawing.Size(600, 938)
$gpoViewButton.Size = New-Object System.Drawing.Size(125, 23)
$gpoViewButton.Text = "Show GPOs"
$OU_GPO_Tool.Controls.Add($gpoViewButton)

$gpoViewButton.Add_Click({

        $selectedUserOU = $userOUDrop.SelectedItem.DistinguishedName
        $selectedComputerOU = $computerOUDrop.SelectedItem.DistinguishedName

        # Calling the GPOs of the chosen OU
        $SearchBaseUser = $selectedUserOU
        $SearchBaseComputer = $selectedComputerOU
        $GPOs = @()
        $GPOsUnique = @()
        $userOUs = Get-ADOrganizationalUnit -SearchBase $SearchBaseUser -Filter *
        $computerOUs = Get-ADOrganizationalUnit -SearchBase $SearchBaseComputer -Filter *
        foreach ($OU in $userOUs) {
            $GPOs += $OU.LinkedGroupPolicyObjects
        }
        foreach ($OU in $computerOUs) {
            $GPOs += $OU.LinkedGroupPolicyObjects
        }
        $GPOsUnique = ($GPOs | Sort-Object -Unique)

        # Check if GPOs are existing
        if ($GPOsUnique.Count -eq 0) {
            $statusTextbox.Text += "No GPOs could be found in the chosen OU.`r`n"
            $statusTextbox.Text += "=========================================================================================================="
        }
        else {
            # Calling the names of the GPOs and displaying them in the outputTextbox
            $GPONames = @()
            foreach ($GPO in $GPOsUnique) {
                $GPOGuid = $GPO -replace '(cn=)|(,cn=policies,cn=system,.*)', ''
                $GPOName = (Get-GPO -Guid $GPOGuid).DisplayName
                $GPONames += $GPOName
            }
            $outputTextbox.Text = $GPONames -join "`r`n"
            $statusTextbox.Text += "The GPOs were showed successfully.`r`n"
            $statusTextbox.Text += "=========================================================================================================="
        }
    })

# Reset Button
$resetButton = New-Object System.Windows.Forms.Button
$resetButton.Location = New-Object System.Drawing.Point(400, 20)
$resetButton.Size = New-Object System.Drawing.Size(100, 23)
$resetButton.Text = "Reset"
$OU_GPO_Tool.Controls.Add($resetButton)

$resetButton.add_Click({
        # Set everything to default (empty boxes)
        $userOUDrop.SelectedIndex = -1
        $computerOUDrop.SelectedIndex = -1
        $siteOUDrop.SelectedIndex = -1
        $newOUTextbox.Clear()
        $inputUserTextbox.Clear()
        $inputComputerTextbox.Clear()
        $outputTextbox.Clear()
        $statusTextbox.Clear()
    })

# Clear Status Button
$clearStatusButton = New-Object System.Windows.Forms.Button
$clearStatusButton.Location = New-Object System.Drawing.Point(1305, 935)
$clearStatusButton.Size = New-Object System.Drawing.Size(100, 23)
$clearStatusButton.Text = "Clear Status"
$OU_GPO_Tool.Controls.Add($clearStatusButton)

$clearStatusButton.add_Click({
        $statusTextbox.Clear()
    })

# Open User File Button
$openUserFileButton = New-Object System.Windows.Forms.Button
$openUserFileButton.Location = New-Object System.Drawing.Point(20, 542)
$openUserFileButton.Size = New-Object System.Drawing.Size(75, 23)
$openUserFileButton.Text = "Open File"
$OU_GPO_Tool.Controls.Add($openUserFileButton) 

$openUserFileDialog = New-Object System.Windows.Forms.OpenFileDialog
$openUserFileDialog.Title = "Please choose a .txt file"
$openUserFileDialog.Filter = "Text Documents (*.txt)|*.txt|All Files (*.*)|*.*"

$openUserFileButton.add_Click({
        if ($openUserFileDialog.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
            $Line_in_file = Get-Content $openUserFileDialog.FileName | Measure-Object –Line
            $x = -1
            do {
                $x++

            }
            while ($Line_in_file -eq $x)

            foreach ($line in [System.IO.File]::ReadLines($openUserFileDialog.FileName)) {
                $inputUserTextbox.Text += "$line`r`n"
            }
        }
    })

# Open Computer File Button
$openComputerFileButton = New-Object System.Windows.Forms.Button
$openComputerFileButton.Location = New-Object System.Drawing.Point(650, 542)
$openComputerFileButton.Size = New-Object System.Drawing.Size(75, 23)
$openComputerFileButton.Text = "Open File"
$OU_GPO_Tool.Controls.Add($openComputerFileButton) 

$openComputerFileDialog = New-Object System.Windows.Forms.OpenFileDialog
$openComputerFileDialog.Title = "Please choose a .txt file"
$openComputerFileDialog.Filter = "Text Documents (*.txt)|*.txt|All Files (*.*)|*.*"

$openComputerFileButton.add_Click({
        if ($openComputerFileDialog.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
            $Line_in_file = Get-Content $openComputerFileDialog.FileName | Measure-Object –Line
            $x = -1
            do {
                $x++

            }
            while ($Line_in_file -eq $x)

            foreach ($line in [System.IO.File]::ReadLines($openComputerFileDialog.FileName)) {
                $inputComputerTextbox.Text += "$line`r`n"
            }
        }
    })


# Sets the directory (where the ps1 / the exe is)
Set-Location -Path $PSScriptRoot

# Button to read the the .txt file in the user folder
$readUserFileButton = New-Object System.Windows.Forms.Button
$readUserFileButton.Location = New-Object System.Drawing.Point(20, 570)
$readUserFileButton.Size = New-Object System.Drawing.Size(125, 23)
$readUserFileButton.Text = "User-GPOs"
$OU_GPO_Tool.Controls.Add($readUserFileButton)

$readUserFileButton.add_Click({
        # Path to user-folder
        $userFolderPath = ".\UserGPOs"
        $latestUserFile = Get-ChildItem -Path $userFolderPath -Filter "*.txt" | Sort-Object LastAccessTime -Descending | Select-Object -First 1
        $inputUserTextbox.Text = Get-Content -Path $latestUserFile.FullName -Raw
    })

# Button to read the the .txt file in the computer folder
$readComputerFileButton = New-Object System.Windows.Forms.Button
$readComputerFileButton.Location = New-Object System.Drawing.Point(600, 570)
$readComputerFileButton.Size = New-Object System.Drawing.Size(125, 23)
$readComputerFileButton.Text = "Computer-GPOs"
$OU_GPO_Tool.Controls.Add($readComputerFileButton)

$readComputerFileButton.add_Click({
        # Path to computer-folder
        $computerFolderPath = ".\ComputerGPOs"
        $latestComputerFile = Get-ChildItem -Path $computerFolderPath -Filter "*.txt" | Sort-Object LastAccessTime -Descending | Select-Object -First 1
        $inputComputerTextbox.Text = Get-Content -Path $latestComputerFile.FullName -Raw
    })

# The cheap "light switch" ^^
$themeSwitchButton = New-Object System.Windows.Forms.Button
$themeSwitchButton.Location = New-Object System.Drawing.Point(1280, 10)
$themeSwitchButton.Size = New-Object System.Drawing.Size(125, 23)
$themeSwitchButton.Text = "Dark Mode"
$OU_GPO_Tool.Controls.Add($themeSwitchButton)

$themeSwitchButton.add_Click({
        if ($OU_GPO_Tool.BackColor -eq [System.Drawing.Color]::White) {
            $OU_GPO_Tool.BackColor = [System.Drawing.Color]::Black
            $title.ForeColor = [System.Drawing.Color]::White
            $descriptionOUChoice.ForeColor = [System.Drawing.Color]::White
            $descriptionStatus.ForeColor = [System.Drawing.Color]::White
            $descriptionOUCreate.ForeColor = [System.Drawing.Color]::White
            $descriptionInput.ForeColor = [System.Drawing.Color]::White
            $descriptionOutput.ForeColor = [System.Drawing.Color]::White
            $descriptionReset.ForeColor = [System.Drawing.Color]::White
            $siteOUDrop.ForeColor = [System.Drawing.Color]::White
            $userOUDrop.ForeColor = [System.Drawing.Color]::White
            $computerOUDrop.ForeColor = [System.Drawing.Color]::White
            $statusTextbox.ForeColor = [System.Drawing.Color]::White
            $newOUTextbox.ForeColor = [System.Drawing.Color]::White
            $inputUserTextbox.ForeColor = [System.Drawing.Color]::White
            $inputComputerTextbox.ForeColor = [System.Drawing.Color]::White
            $outputTextbox.ForeColor = [System.Drawing.Color]::White
            $progressBar.ForeColor = [System.Drawing.Color]::White
            $newOUButton.ForeColor = [System.Drawing.Color]::White
            $newUaCOUButton.ForeColor = [System.Drawing.Color]::White
            $addUserButton.ForeColor = [System.Drawing.Color]::White
            $addComputerButton.ForeColor = [System.Drawing.Color]::White
            $addBothButton.ForeColor = [System.Drawing.Color]::White
            $gpoViewButton.ForeColor = [System.Drawing.Color]::White
            $resetButton.ForeColor = [System.Drawing.Color]::White
            $clearStatusButton.ForeColor = [System.Drawing.Color]::White
            $openUserFileButton.ForeColor = [System.Drawing.Color]::White
            $openComputerFileButton.ForeColor = [System.Drawing.Color]::White
            $readUserFileButton.ForeColor = [System.Drawing.Color]::White
            $readComputerFileButton.ForeColor = [System.Drawing.Color]::White
            $themeSwitchButton.ForeColor = [System.Drawing.Color]::White
            $title.BackColor = [System.Drawing.Color]::Black
            $descriptionOUChoice.BackColor = [System.Drawing.Color]::Black
            $descriptionStatus.BackColor = [System.Drawing.Color]::Black
            $descriptionOUCreate.BackColor = [System.Drawing.Color]::Black
            $descriptionInput.BackColor = [System.Drawing.Color]::Black
            $descriptionOutput.BackColor = [System.Drawing.Color]::Black
            $descriptionReset.BackColor = [System.Drawing.Color]::Black
            $siteOUDrop.BackColor = [System.Drawing.Color]::Black
            $userOUDrop.BackColor = [System.Drawing.Color]::Black
            $computerOUDrop.BackColor = [System.Drawing.Color]::Black
            $statusTextbox.BackColor = [System.Drawing.Color]::Black
            $newOUTextbox.BackColor = [System.Drawing.Color]::Black
            $inputUserTextbox.BackColor = [System.Drawing.Color]::Black
            $inputComputerTextbox.BackColor = [System.Drawing.Color]::Black
            $outputTextbox.BackColor = [System.Drawing.Color]::Black
            $progressBar.BackColor = [System.Drawing.Color]::Black
            $newOUButton.BackColor = [System.Drawing.Color]::Black
            $newUaCOUButton.BackColor = [System.Drawing.Color]::Black
            $addUserButton.BackColor = [System.Drawing.Color]::Black
            $addComputerButton.BackColor = [System.Drawing.Color]::Black
            $addBothButton.BackColor = [System.Drawing.Color]::Black
            $gpoViewButton.BackColor = [System.Drawing.Color]::Black
            $resetButton.BackColor = [System.Drawing.Color]::Black
            $clearStatusButton.BackColor = [System.Drawing.Color]::Black
            $openUserFileButton.BackColor = [System.Drawing.Color]::Black
            $openComputerFileButton.BackColor = [System.Drawing.Color]::Black
            $readUserFileButton.BackColor = [System.Drawing.Color]::Black
            $readComputerFileButton.BackColor = [System.Drawing.Color]::Black
            $themeSwitchButton.BackColor = [System.Drawing.Color]::Black
            $themeSwitchButton.Text = "Light Mode"
        } 
        elseif ($OU_GPO_Tool.BackColor -eq [System.Drawing.Color]::Black) {
            $OU_GPO_Tool.BackColor = [System.Drawing.Color]::White
            $title.ForeColor = [System.Drawing.Color]::Black
            $descriptionOUChoice.ForeColor = [System.Drawing.Color]::Black
            $descriptionStatus.ForeColor = [System.Drawing.Color]::Black
            $descriptionOUCreate.ForeColor = [System.Drawing.Color]::Black
            $descriptionInput.ForeColor = [System.Drawing.Color]::Black
            $descriptionOutput.ForeColor = [System.Drawing.Color]::Black
            $descriptionReset.ForeColor = [System.Drawing.Color]::Black
            $siteOUDrop.ForeColor = [System.Drawing.Color]::Black
            $userOUDrop.ForeColor = [System.Drawing.Color]::Black
            $computerOUDrop.ForeColor = [System.Drawing.Color]::Black
            $statusTextbox.ForeColor = [System.Drawing.Color]::Black
            $newOUTextbox.ForeColor = [System.Drawing.Color]::Black
            $inputUserTextbox.ForeColor = [System.Drawing.Color]::Black
            $inputComputerTextbox.ForeColor = [System.Drawing.Color]::Black
            $outputTextbox.ForeColor = [System.Drawing.Color]::Black
            $progressBar.ForeColor = [System.Drawing.Color]::Black
            $newOUButton.ForeColor = [System.Drawing.Color]::Black
            $newUaCOUButton.ForeColor = [System.Drawing.Color]::Black
            $addUserButton.ForeColor = [System.Drawing.Color]::Black
            $addComputerButton.ForeColor = [System.Drawing.Color]::Black
            $addBothButton.ForeColor = [System.Drawing.Color]::Black
            $gpoViewButton.ForeColor = [System.Drawing.Color]::Black
            $resetButton.ForeColor = [System.Drawing.Color]::Black
            $clearStatusButton.ForeColor = [System.Drawing.Color]::Black
            $openUserFileButton.ForeColor = [System.Drawing.Color]::Black
            $openComputerFileButton.ForeColor = [System.Drawing.Color]::Black
            $readUserFileButton.ForeColor = [System.Drawing.Color]::Black
            $readComputerFileButton.ForeColor = [System.Drawing.Color]::Black
            $themeSwitchButton.ForeColor = [System.Drawing.Color]::Black
            $title.BackColor = [System.Drawing.Color]::White
            $descriptionOUChoice.BackColor = [System.Drawing.Color]::White
            $descriptionStatus.BackColor = [System.Drawing.Color]::White
            $descriptionOUCreate.BackColor = [System.Drawing.Color]::White
            $descriptionInput.BackColor = [System.Drawing.Color]::White
            $descriptionOutput.BackColor = [System.Drawing.Color]::White
            $descriptionReset.BackColor = [System.Drawing.Color]::White
            $siteOUDrop.BackColor = [System.Drawing.Color]::White
            $userOUDrop.BackColor = [System.Drawing.Color]::White
            $computerOUDrop.BackColor = [System.Drawing.Color]::White
            $statusTextbox.BackColor = [System.Drawing.Color]::White
            $newOUTextbox.BackColor = [System.Drawing.Color]::White
            $inputUserTextbox.BackColor = [System.Drawing.Color]::White
            $inputComputerTextbox.BackColor = [System.Drawing.Color]::White
            $outputTextbox.BackColor = [System.Drawing.Color]::White
            $progressBar.BackColor = [System.Drawing.Color]::White
            $newOUButton.BackColor = [System.Drawing.Color]::White
            $newUaCOUButton.BackColor = [System.Drawing.Color]::White
            $addUserButton.BackColor = [System.Drawing.Color]::White
            $addComputerButton.BackColor = [System.Drawing.Color]::White
            $addBothButton.BackColor = [System.Drawing.Color]::White
            $gpoViewButton.BackColor = [System.Drawing.Color]::White
            $resetButton.BackColor = [System.Drawing.Color]::White
            $clearStatusButton.BackColor = [System.Drawing.Color]::White
            $openUserFileButton.BackColor = [System.Drawing.Color]::White
            $openComputerFileButton.BackColor = [System.Drawing.Color]::White
            $readUserFileButton.BackColor = [System.Drawing.Color]::White
            $readComputerFileButton.BackColor = [System.Drawing.Color]::White
            $themeSwitchButton.BackColor = [System.Drawing.Color]::White
            $themeSwitchButton.Text = "Dark Mode"
        }
    })


# Display the form --------------------------------------------------------------------------------------------------------------------
[void]$OU_GPO_Tool.ShowDialog()